### ISSUE TITLE
[EPIC] User Dashboard

### ISSUE THREAD

**Issue by JoshuaChing** [ProjectTwentyFive/task-sourcing#13]
TODO:
- [x] View my tasks***
- [x] link to create a new task***
- [x] link task to individual task page***
- [x] View my pending bids***
- [x] link to view all tasks***
- [x] link bid to individual task page https://github.com/ProjectTwentyFive/task-sourcing/issues/41
- [x] View assigned tasks
- [x] View completed tasks

MINOR FIXES:
- [x] show status of my tasks instead of the id (0, 1, 2)
- [x] change your bids to pending bids (only show opened bids)
- [x] remove selected column for your pending bids and show end date instead
- [x] button that links to editing task

*** these issues were completed before the time of this epic

**Comment by justinhw** [comment]
Please add to dashboard: 

- Your 'Assigned Tasks' 
- Your 'Created Tasks'
