### ISSUE TITLE
[EPIC] REST Interface for Bids

### ISSUE THREAD

**Issue by jjamay** [ProjectTwentyFive/task-sourcing#4]
As a user:
- [x] create a bid***
- [x] view all details of a bid***
- [x] update my bid (select a winner) https://github.com/ProjectTwentyFive/task-sourcing/issues/15
- [x] delete my bid https://github.com/ProjectTwentyFive/task-sourcing/issues/22

*** these issues were created before the time of this epic
