### ISSUE TITLE
[EPIC] REST Interface for Tasks

### ISSUE THREAD

**Issue by jjamay** [ProjectTwentyFive/task-sourcing#6]
As a user:
- [x] create task***
- [x] view all details of a task https://github.com/ProjectTwentyFive/task-sourcing/issues/31
- [x] update task https://github.com/ProjectTwentyFive/task-sourcing/issues/33
- [x] delete task https://github.com/ProjectTwentyFive/task-sourcing/issues/32

*** these issues were created before the time of this epic

**Comment by jjamay** [comment]
I'm doing this rn so I assignment myself
